# 站点设置
site:
  name: ROY               # 左上角首页名称
  icon: /img/royians/avatar.jpg # 页脚的icon
  icp:                    # ICP
  siteIcon: /img/royians/logo.png # 主页的icon
  uri: little-dream.land


# 导航栏
nav:
#导航栏左侧
  left:
    enable: true
    menu:
      我的:
        个人主页:
          icon: /img/avatar.webp
          url: https://royians.cn/
# 导航栏内容
  menu:
    文库:
      url: false
      child:
        文章列表:
          url: /archives/
          icon: ri-archive-fill
        全部分类:
          url: /categories/
          icon: ri-apps-fill
        全部标签:
          url: /tags/
          icon: ri-price-tag-3-fill
    留言:
      url: /comments
      icon: ri-chat-smile-2-line
    关于:
      url: false
      child:
        关于我:
          url: /about
          icon: ri-emotion-laugh-line
        个人主页:
          icon: ri-home-heart-line
          url: https://royians.cn/
    友链:
      url: false
      child:
        友情链接:
          url: /links/
          icon: ri-link-m
        宝藏博主:
          url: javascript:travelling()
          icon: ri-star-smile-fill

# 导航栏右侧快捷菜单
  right: # @todo 允许用户自定义
    travellings: true
    random: true
    search: true
    console: true


# heo式顶部一大坨
hometop:
  bbtime: true
  banner:
    title: 记录生活<br>的点点滴滴
    url: little-dream.land
    icon:
      AE:
        img: /img/icon/ae.png
        color: '#989bf8'
      Sketch:
        img: /img/icon/Sketch.png
        color: '#ffffff'
      Docker:
        img: /img/icon/docker.png
        color: '#57b6e6'
      ps:
        img: /img/icon/ps.png
        color: '#4082c3'
      FinalCutPro:
        img: /img/icon/FinalCutPro.png
        color: '#ffffff'
      Python:
        img: /img/icon/Python.png
        color: '#ffffff'
      Swift:
        img: /img/icon/Swift.png
        color: '#eb6840'
      Principle:
        img: /img/icon/Principle.png
        color: '#8f55ba'
      illustrator:
        img: /img/icon/illustrator.png
        color: '#f29e39'
      CSS3:
        img: /img/icon/CSS3.png
        color: '#2c51db'
      JS:
        img: /img/icon/JS.png
        color: '#f7cb4f'
      Git:
        img: /img/icon/git.png
        color: '#df5b40'

  categoryGroup:
    G1:
      name: 随摄
      icon: ri-dv-fill
      url: /tags/随摄/
    G2:
      name: 随想
      icon: ri-user-voice-fill
      url: /tags/随想/
    G3:
      name: 随记
      icon: ri-book-2-fill
      url: /tags/随记/

  recommendList:
    sup: 置顶文章
    title: 酷安文化衫设计
    url: /posts/2017082201/
    img: /images/covers/2017/08/2201.webp
    color: '#212121'

# 个人卡片
aside:
  card:
    content: 欢迎来到<b>小梦岛</b>，这里记录我的<b>日常生活</b>、<b>个人想法</b>和<b>学习记录</b><br>感谢你参观我的博客，我使用的博客主题是<b><a href="https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic" target="_blank">Acrylic</a></b>。
    information:
      Github:
        icon: ri-github-fill
        url: https://github.com/ROYIANS
      微信公众号:
        icon: ri-wechat-2-fill
        url: https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=MzIxODQ1OTU0OQ==&scene=124#wechat_redirect
    button:
      text: 个人主页
      url: https://www.royians.cn/
# 建站时间
  analytics:
    runtime: '2018-01-01 00:00:00'

# 页脚
footer:
  information:
    left:
      微博:
        icon: ri-weibo-line
        url: https://weibo.com/u/6319184855
      哔哩哔哩:
        icon: ri-bilibili-line
        url: https://space.bilibili.com/32267413
    right:
      网易云:
        icon: ri-netease-cloud-music-line
        url: https://y.music.163.com/m/user?id=356590959&dlt=0846&app_version=8.9.10
      tg:
        icon: ri-telegram-line
        url: https://t.me/s/littleDreamlandPlus

  group:
    导航:
      文章归档: /archives/
      文章分类: /categories/
      文章标签: /tags/
      友链: /links/
    其他网页:
      PROGRAMADOR: https://programador.cn/
      VIDORRA: https://vidorra.cn/
    个人项目:
      打印模板设计器: https://gitee.com/ROYIANS/print-template-designer
    推荐友链:
      Heo: https://blog.zhheo.com/
      Akilar: https://akilar.top

  randomlink: true


# 文章页默认设置
post:
  default:
    cover: /img/hello.jpg
    locate: 太原
    copyright: 原创
    excerpt: 100
  award:
    enable: false
    wechat:
    alipay:
    url:

# 404
errorpage:
  img: /images/404.webp
  text: =qwq= 你好像迷路了
  recommendList: true

# 懒加载
lazyload:
  enable: true
  placeholder: /img/dribble-shot-load-screen.gif
  errorimg: /img/dribble-shot-load-screen.gif

# 加载动画
loading:
  enable: false
  pace: true

# 第三方设置
thirdparty:
  wordcount: true

# 评论
comment:
  enable: true
  twikoo:
    envId: https://twikoo.little-dream.land/
    visitor: true

# 插入代码到头部 </head> 之前 和 底部 </body> 之前
# 插入额外代码 如：统计，广告等
extends:
  head: # 在head中插入
     - <link href="/fonts/remixicon.css" rel="stylesheet">
     - <link href="/fonts/ROYIANS/ROYIANS.css" rel="stylesheet">
     - <link href="/fonts/LDL/LDL.css" rel="stylesheet">
     - <link href="/css/heti.min.css" rel="stylesheet">
     - <link rel="preconnect" href="https://fonts.googleapis.com">
     - <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
     - <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+SC&family=Noto+Serif+SC&display=swap" rel="stylesheet">
     - <script>var _hmt=_hmt||[];(function(){var hm=document.createElement("script");hm.src="https://hm.baidu.com/hm.js?fe2db955cb6ff96a6e53b812ac5e9559";var s=document.getElementsByTagName("script")[0];s.parentNode.insertBefore(hm,s)})();</script>
     - <!--Google tag(gtag.js)--><script async src="https://www.googletagmanager.com/gtag/js?id=G-8CY7HEN598"></script><script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag('js',new Date());gtag('config','G-8CY7HEN598');</script>
  body: # 在body中插入

sakana:
  enable: true

# 非必要勿动
cdn:
  head:
    pacejs: https://lf6-cdn-tos.bytecdntp.com/cdn/expire-1-M/pace/1.2.4/pace.min.js
    fontawesomecss: https://cdn.bootcdn.net/ajax/libs/font-awesome/6.3.0/css/all.min.css
    snackbarcss: /lib/snackbar.min.css
    qrcodejs: /lib/qrcode.min.js
    twikoojs: https://cdn.staticfile.org/twikoo/1.6.10/twikoo.all.min.js
    sakanacss: https://cdn.jsdelivr.net/npm/sakana-widget@2.5.0/lib/sakana.min.css
    sakanajs: https://cdn.jsdelivr.net/npm/sakana-widget@2.5.0/lib/sakana.min.js
  body:
    swipercss: /lib/swiper.min.css
    pjaxjs: /lib/pjax.min.js
    lazyloadjs: /lib/lazyload.min.js
    snackbarjs: /lib/snackbar.min.js
    viewimagejs: /lib/view-image.min.js
    waterfalljs: /lib/waterfall.min.js
    swiperjs: /lib/swiper.min.js
